create table game_tag (
    id bigint generated by default as identity primary key,
    category varchar(32) not null,
    code varchar(64) not null unique,
    name varchar(64) not null,
    status varchar(16) not null default 'ACTIVE',
    sort_order int not null default 0,
    created_at timestamp not null
);

create table game_product_tag (
    game_id bigint not null,
    tag_id bigint not null,
    created_at timestamp not null,
    constraint pk_game_product_tag primary key (game_id, tag_id),
    constraint fk_gpt_game foreign key (game_id) references game_product(id),
    constraint fk_gpt_tag foreign key (tag_id) references game_tag(id)
);
