create table teacher_class (
    id bigint generated by default as identity primary key,
    teacher_id bigint not null,
    class_name varchar(64) not null,
    monitor_name varchar(64),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_teacher_class_teacher foreign key (teacher_id) references app_user(id),
    constraint uk_teacher_class unique (teacher_id, class_name)
);
