spring:
  profiles:
    default: local
  application:
    name: eduplay-backend
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

eduplay:
  plugins:
    package-dir: ${EDUPLAY_PLUGIN_PACKAGE_DIR:./plugins/packages}
    install-dir: ${EDUPLAY_PLUGIN_INSTALL_DIR:./plugins/installed}

logging:
  level:
    org.hibernate.SQL: info
